import type { IMember } from './types';

export const members_ru: IMember[] = [
    {
        id: 1,
        store_id: 1,
        photo: '',
        full_name: 'Иванов Сергей Петрович',
        position: 'Кладовщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 180000,
    },
    {
        id: 2,
        store_id: 2,
        photo: '',
        full_name: 'Петрова Марина Алексеевна',
        position: 'Оператор склада',
        schedule: 'ПН-ПТ 09:00-18:00',
        holiday: false,
        salary: 175000,
    },
    {
        id: 3,
        store_id: 3,
        photo: '',
        full_name: 'Сидоров Алексей Николаевич',
        position: 'Грузчик',
        schedule: 'ПН-СБ 07:00-16:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 4,
        store_id: 4,
        photo: '',
        full_name: 'Михайлова Анна Васильевна',
        position: 'Упаковщик',
        schedule: 'ПН-ПТ 08:30-17:30',
        holiday: false,
        salary: 165000,
    },
    {
        id: 5,
        store_id: 1,
        photo: '',
        full_name: 'Кузнецов Дмитрий Олегович',
        position: 'Приемщик товара',
        schedule: 'ВТ-СБ 09:00-18:00',
        holiday: false,
        salary: 170000,
    },
    {
        id: 6,
        store_id: 2,
        photo: '',
        full_name: 'Алексеева Елена Викторовна',
        position: 'Кладовщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 180000,
    },
    {
        id: 7,
        store_id: 3,
        photo: '',
        full_name: 'Тимофеев Артём Игоревич',
        position: 'Грузчик',
        schedule: 'ПН-СБ 07:00-16:00',
        holiday: true,
        salary: 150000,
    },
    {
        id: 8,
        store_id: 4,
        photo: '',
        full_name: 'Горбунова Ольга Сергеевна',
        position: 'Оператор склада',
        schedule: 'ПН-ПТ 09:00-18:00',
        holiday: false,
        salary: 175000,
    },
    {
        id: 9,
        store_id: 1,
        photo: '',
        full_name: 'Орлов Николай Евгеньевич',
        position: 'Комплектовщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 165000,
    },
    {
        id: 10,
        store_id: 2,
        photo: '',
        full_name: 'Романова Светлана Викторовна',
        position: 'Упаковщик',
        schedule: 'ПН-ПТ 08:30-17:30',
        holiday: false,
        salary: 165000,
    },
    {
        id: 11,
        store_id: 3,
        photo: '',
        full_name: 'Беляев Константин Михайлович',
        position: 'Водитель погрузчика',
        schedule: 'ПН-СБ 06:00-15:00',
        holiday: false,
        salary: 185000,
    },
    {
        id: 12,
        store_id: 4,
        photo: '',
        full_name: 'Зайцева Дарья Ильинична',
        position: 'Сортировщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 13,
        store_id: 1,
        photo: '',
        full_name: 'Смирнов Андрей Васильевич',
        position: 'Кладовщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 180000,
    },
    {
        id: 14,
        store_id: 2,
        photo: '',
        full_name: 'Мельникова Ксения Олеговна',
        position: 'Оператор склада',
        schedule: 'ПН-ПТ 09:00-18:00',
        holiday: true,
        salary: 170000,
    },
    {
        id: 15,
        store_id: 3,
        photo: '',
        full_name: 'Егоров Тимур Романович',
        position: 'Грузчик',
        schedule: 'ПН-СБ 07:00-16:00',
        holiday: false,
        salary: 155000,
    },
    {
        id: 16,
        store_id: 4,
        photo: '',
        full_name: 'Николаева Мария Павловна',
        position: 'Упаковщик',
        schedule: 'ПН-ПТ 08:30-17:30',
        holiday: false,
        salary: 165000,
    },
    {
        id: 17,
        store_id: 1,
        photo: '',
        full_name: 'Федоров Владислав Юрьевич',
        position: 'Комплектовщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 18,
        store_id: 2,
        photo: '',
        full_name: 'Анисимова Елизавета Николаевна',
        position: 'Сортировщик',
        schedule: 'ПН-ПТ 08:00-17:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 19,
        store_id: 3,
        photo: '',
        full_name: 'Григорьев Денис Аркадьевич',
        position: 'Водитель погрузчика',
        schedule: 'ПН-СБ 06:00-15:00',
        holiday: false,
        salary: 185000,
    },
    {
        id: 20,
        store_id: 4,
        photo: '',
        full_name: 'Волкова Анастасия Сергеевна',
        position: 'Оператор склада',
        schedule: 'ПН-ПТ 09:00-18:00',
        holiday: false,
        salary: 170000,
    },
];
