import type { IMember } from './types';

export const members_en: IMember[] = [
    {
        id: 1,
        store_id: 1,
        photo: '',
        full_name: 'Sergey Ivanov',
        position: 'Warehouse Manager',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 180000,
    },
    {
        id: 2,
        store_id: 2,
        photo: '',
        full_name: 'Marina Petrova',
        position: 'Warehouse Operator',
        schedule: 'MON-FRI 09:00-18:00',
        holiday: false,
        salary: 175000,
    },
    {
        id: 3,
        store_id: 3,
        photo: '',
        full_name: 'Alexey Sidorov',
        position: 'Loader',
        schedule: 'MON-SAT 07:00-16:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 4,
        store_id: 4,
        photo: '',
        full_name: 'Anna Mikhailova',
        position: 'Packer',
        schedule: 'MON-FRI 08:30-17:30',
        holiday: false,
        salary: 165000,
    },
    {
        id: 5,
        store_id: 1,
        photo: '',
        full_name: 'Dmitry Kuznetsov',
        position: 'Goods Receiver',
        schedule: 'TUE-SAT 09:00-18:00',
        holiday: false,
        salary: 170000,
    },
    {
        id: 6,
        store_id: 2,
        photo: '',
        full_name: 'Elena Alexeeva',
        position: 'Warehouse Manager',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 180000,
    },
    {
        id: 7,
        store_id: 3,
        photo: '',
        full_name: 'Artyom Timofeev',
        position: 'Loader',
        schedule: 'MON-SAT 07:00-16:00',
        holiday: true,
        salary: 150000,
    },
    {
        id: 8,
        store_id: 4,
        photo: '',
        full_name: 'Olga Gorbunova',
        position: 'Warehouse Operator',
        schedule: 'MON-FRI 09:00-18:00',
        holiday: false,
        salary: 175000,
    },
    {
        id: 9,
        store_id: 1,
        photo: '',
        full_name: 'Nikolay Orlov',
        position: 'Picker',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 165000,
    },
    {
        id: 10,
        store_id: 2,
        photo: '',
        full_name: 'Svetlana Romanova',
        position: 'Packer',
        schedule: 'MON-FRI 08:30-17:30',
        holiday: false,
        salary: 165000,
    },
    {
        id: 11,
        store_id: 3,
        photo: '',
        full_name: 'Konstantin Belyaev',
        position: 'Forklift Operator',
        schedule: 'MON-SAT 06:00-15:00',
        holiday: false,
        salary: 185000,
    },
    {
        id: 12,
        store_id: 4,
        photo: '',
        full_name: 'Darya Zaitseva',
        position: 'Sorter',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 13,
        store_id: 1,
        photo: '',
        full_name: 'Andrey Smirnov',
        position: 'Warehouse Manager',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 180000,
    },
    {
        id: 14,
        store_id: 2,
        photo: '',
        full_name: 'Kseniya Melnikova',
        position: 'Warehouse Operator',
        schedule: 'MON-FRI 09:00-18:00',
        holiday: true,
        salary: 170000,
    },
    {
        id: 15,
        store_id: 3,
        photo: '',
        full_name: 'Timur Egorov',
        position: 'Loader',
        schedule: 'MON-SAT 07:00-16:00',
        holiday: false,
        salary: 155000,
    },
    {
        id: 16,
        store_id: 4,
        photo: '',
        full_name: 'Maria Nikolaeva',
        position: 'Packer',
        schedule: 'MON-FRI 08:30-17:30',
        holiday: false,
        salary: 165000,
    },
    {
        id: 17,
        store_id: 1,
        photo: '',
        full_name: 'Vladislav Fedorov',
        position: 'Picker',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 18,
        store_id: 2,
        photo: '',
        full_name: 'Elizaveta Anisimova',
        position: 'Sorter',
        schedule: 'MON-FRI 08:00-17:00',
        holiday: false,
        salary: 160000,
    },
    {
        id: 19,
        store_id: 3,
        photo: '',
        full_name: 'Denis Grigoryev',
        position: 'Forklift Operator',
        schedule: 'MON-SAT 06:00-15:00',
        holiday: false,
        salary: 185000,
    },
    {
        id: 20,
        store_id: 4,
        photo: '',
        full_name: 'Anastasia Volkova',
        position: 'Warehouse Operator',
        schedule: 'MON-FRI 09:00-18:00',
        holiday: false,
        salary: 170000,
    },
];
