import type { IProduct } from "~/types";

export const products_en: IProduct[] = [
    {
        "id": 1,
        "store_id": 1,
        "category": "Electronics",
        "photo": "/products/product_1.jpg",
        "title": "Smartphone",
        "short_desc": "High-end smartphone with great features",
        "count": 50,
        "price": 699,
        "currency": "USD",
        "status": "STOCK_PENDING",
        "time_arrive": "02.01.2025 ~08:00-10:00",
        "time_send": null,
        "sell_count": 25,
        "send_count": 0,
        "arrive_count": 50
    },
    {
        "id": 2,
        "store_id": 2,
        "category": "Books",
        "photo": "/products/product_2.jpg",
        "title": "Fiction Novel",
        "short_desc": "Bestselling fiction book of the year",
        "count": 0,
        "price": 19.99,
        "currency": "USD",
        "status": "SELL",
        "time_arrive": "01.12.2024 ~12:00-14:00",
        "time_send": null,
        "sell_count": 100,
        "send_count": 0,
        "arrive_count": 100
    },
    {
        "id": 3,
        "store_id": 3,
        "category": "Clothing",
        "photo": "/products/product_3.jpg",
        "title": "T-Shirt",
        "short_desc": "Comfortable cotton T-shirt",
        "count": 0,
        "price": 15.99,
        "currency": "USD",
        "status": "NOT_AVAILABLE",
        "time_arrive": null,
        "time_send": null,
        "sell_count": 75,
        "send_count": 0,
        "arrive_count": 75
    },
    {
        "id": 4,
        "store_id": 4,
        "category": "Toys",
        "photo": "/products/product_4.jpg",
        "title": "Action Figure",
        "short_desc": "Popular action figure for kids",
        "count": 30,
        "price": 25.99,
        "currency": "USD",
        "status": "SEND",
        "time_arrive": "01.05.2024 ~10:00-12:00",
        "time_send": "05.05.2024 ~15:00-16:30",
        "sell_count": 15,
        "send_count": 30,
        "arrive_count": 30
    },
    {
        "id": 5,
        "store_id": 1,
        "category": "Furniture",
        "photo": "/products/product_5.jpg",
        "title": "Office Chair",
        "short_desc": "Ergonomic office chair for long hours",
        "count": 20,
        "price": 199.99,
        "currency": "USD",
        "status": "ARRIVED",
        "time_arrive": "27.06.2024 ~08:30-10:30",
        "time_send": null,
        "sell_count": 10,
        "send_count": 0,
        "arrive_count": 30
    },
    {
        "id": 6,
        "store_id": 2,
        "category": "Electronics",
        "photo": "/products/product_6.jpg",
        "title": "Laptop",
        "short_desc": "High-performance laptop for gaming",
        "count": 10,
        "price": 1200,
        "currency": "USD",
        "status": "STOCK_PENDING",
        "time_arrive": "12.01.2025 ~09:00-11:30",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 15
    },
    {
        "id": 7,
        "store_id": 3,
        "category": "Books",
        "photo": "/products/product_7.jpg",
        "title": "Historical Novel",
        "short_desc": "An epic historical fiction novel",
        "count": 60,
        "price": 22.99,
        "currency": "USD",
        "status": "SELL",
        "time_arrive": "15.11.2024 ~11:00-13:00",
        "time_send": null,
        "sell_count": 40,
        "send_count": 0,
        "arrive_count": 60
    },
    {
        "id": 8,
        "store_id": 4,
        "category": "Clothing",
        "photo": "/products/product_8.jpg",
        "title": "Jeans",
        "short_desc": "Stylish and durable jeans",
        "count": 40,
        "price": 49.99,
        "currency": "USD",
        "status": "ARRIVED",
        "time_arrive": "04.01.2025 ~08:00-10:00",
        "time_send": null,
        "sell_count": 20,
        "send_count": 0,
        "arrive_count": 60
    },
    {
        "id": 9,
        "store_id": 1,
        "category": "Toys",
        "photo": "/products/product_9.jpg",
        "title": "Board Game",
        "short_desc": "Fun board game for family and friends",
        "count": 25,
        "price": 34.99,
        "currency": "USD",
        "status": "SEND",
        "time_arrive": "10.02.2025 ~10:00-12:00",
        "time_send": "11.02.2025 ~13:00-15:00",
        "sell_count": 5,
        "send_count": 25,
        "arrive_count": 30
    },
    {
        "id": 10,
        "store_id": 2,
        "category": "Furniture",
        "photo": "/products/product_10.jpg",
        "title": "Desk",
        "short_desc": "Spacious wooden desk",
        "count": 15,
        "price": 149.99,
        "currency": "USD",
        "status": "STOCK_PENDING",
        "time_arrive": "14.02.2025 ~09:00-11:30",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 20
    },
    {
        "id": 11,
        "store_id": 3,
        "category": "Electronics",
        "photo": "/products/product_11.jpg",
        "title": "Headphones",
        "short_desc": "Wireless headphones with noise cancellation",
        "count": 0,
        "price": 199,
        "currency": "USD",
        "status": "SELL",
        "time_arrive": "10.12.2024 ~10:00-12:00",
        "time_send": null,
        "sell_count": 80,
        "send_count": 0,
        "arrive_count": 80
    },
    {
        "id": 12,
        "store_id": 1,
        "category": "Furniture",
        "photo": "/products/product_12.jpg",
        "title": "Bookshelf",
        "short_desc": "Modern wooden bookshelf",
        "count": 15,
        "price": 99.99,
        "currency": "USD",
        "status": "ARRIVED",
        "time_arrive": "15.12.2024 ~09:00-11:30",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 20
    },
    {
        "id": 13,
        "store_id": 4,
        "category": "Toys",
        "photo": "/products/product_13.jpg",
        "title": "Puzzle",
        "short_desc": "Challenging puzzle for all ages",
        "count": 50,
        "price": 14.99,
        "currency": "USD",
        "status": "SELL",
        "time_arrive": "20.11.2024 ~12:00-14:00",
        "time_send": "25.11.2024 ~13:00-15:00",
        "sell_count": 25,
        "send_count": 25,
        "arrive_count": 50
    },
    {
        "id": 14,
        "store_id": 2,
        "category": "Clothing",
        "photo": "/products/product_14.jpg",
        "title": "Winter Jacket",
        "short_desc": "Warm and stylish winter jacket",
        "count": 10,
        "price": 89.99,
        "currency": "USD",
        "status": "ARRIVED",
        "time_arrive": "01.01.2025 ~08:00-10:00",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 10
    },
    {
        "id": 15,
        "store_id": 3,
        "category": "Books",
        "photo": "/products/product_15.jpg",
        "title": "Cookbook",
        "short_desc": "Recipes for quick and delicious meals",
        "count": 30,
        "price": 24.99,
        "currency": "USD",
        "status": "STOCK_PENDING",
        "time_arrive": "25.01.2025 ~10:00-12:00",
        "time_send": null,
        "sell_count": 0,
        "send_count": 0,
        "arrive_count": 30
    }
]
