import { ProductStatus } from "~/types"
import type { IProduct } from "~/types";

export const products_ru: IProduct[] = [
    {
        "id": 1,
        "store_id": 1,
        "category": "Электроника",
        "photo": "/products/product_1.jpg",
        "title": "Смартфон",
        "short_desc": "Флагманский смартфон с отличными характеристиками",
        "count": 50,
        "price": 699,
        "currency": "USD",
        "status": ProductStatus.STOCK_PENDING,
        "time_arrive": "02.01.2025 ~08:00-10:00",
        "time_send": null,
        "sell_count": 25,
        "send_count": 0,
        "arrive_count": 50
    },
    {
        "id": 2,
        "store_id": 2,
        "category": "Книги",
        "photo": "/products/product_2.jpg",
        "title": "Роман",
        "short_desc": "Бестселлер года",
        "count": 0,
        "price": 19.99,
        "currency": "USD",
        "status": ProductStatus.SELL,
        "time_arrive": "01.12.2024 ~12:00-14:00",
        "time_send": null,
        "sell_count": 100,
        "send_count": 0,
        "arrive_count": 100
    },
    {
        "id": 3,
        "store_id": 3,
        "category": "Одежда",
        "photo": "/products/product_3.jpg",
        "title": "Футболка",
        "short_desc": "Удобная хлопковая футболка",
        "count": 0,
        "price": 15.99,
        "currency": "USD",
        "status": ProductStatus.NOT_AVAILABLE,
        "time_arrive": null,
        "time_send": null,
        "sell_count": 75,
        "send_count": 0,
        "arrive_count": 75
    },
    {
        "id": 4,
        "store_id": 4,
        "category": "Игрушки",
        "photo": "/products/product_4.jpg",
        "title": "Фигурка героя",
        "short_desc": "Популярная фигурка для детей",
        "count": 30,
        "price": 25.99,
        "currency": "USD",
        "status": ProductStatus.SEND,
        "time_arrive": "01.05.2024 ~10:00-12:00",
        "time_send": "05.05.2024 ~15:00-16:30",
        "sell_count": 15,
        "send_count": 30,
        "arrive_count": 30
    },
    {
        "id": 5,
        "store_id": 1,
        "category": "Мебель",
        "photo": "/products/product_5.jpg",
        "title": "Офисное кресло",
        "short_desc": "Эргономичное кресло для долгой работы",
        "count": 20,
        "price": 199.99,
        "currency": "USD",
        "status": ProductStatus.ARRIVED,
        "time_arrive": "27.06.2024 ~08:30-10:30",
        "time_send": null,
        "sell_count": 10,
        "send_count": 0,
        "arrive_count": 30
    },
    {
        "id": 6,
        "store_id": 2,
        "category": "Электроника",
        "photo": "/products/product_6.jpg",
        "title": "Ноутбук",
        "short_desc": "Игровой ноутбук высокой производительности",
        "count": 10,
        "price": 1200,
        "currency": "USD",
        "status": ProductStatus.STOCK_PENDING,
        "time_arrive": "12.01.2025 ~09:00-11:30",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 15
    },
    {
        "id": 7,
        "store_id": 3,
        "category": "Книги",
        "photo": "/products/product_7.jpg",
        "title": "Исторический роман",
        "short_desc": "Эпический исторический роман",
        "count": 60,
        "price": 22.99,
        "currency": "USD",
        "status": ProductStatus.SELL,
        "time_arrive": "15.11.2024 ~11:00-13:00",
        "time_send": null,
        "sell_count": 40,
        "send_count": 0,
        "arrive_count": 60
    },
    {
        "id": 8,
        "store_id": 4,
        "category": "Одежда",
        "photo": "/products/product_8.jpg",
        "title": "Джинсы",
        "short_desc": "Модные и прочные джинсы",
        "count": 40,
        "price": 49.99,
        "currency": "USD",
        "status": ProductStatus.ARRIVED,
        "time_arrive": "04.01.2025 ~08:00-10:00",
        "time_send": null,
        "sell_count": 20,
        "send_count": 0,
        "arrive_count": 60
    },
    {
        "id": 9,
        "store_id": 1,
        "category": "Игрушки",
        "photo": "/products/product_9.jpg",
        "title": "Настольная игра",
        "short_desc": "Веселая игра для семьи и друзей",
        "count": 25,
        "price": 34.99,
        "currency": "USD",
        "status": ProductStatus.SEND,
        "time_arrive": "10.02.2025 ~10:00-12:00",
        "time_send": "11.02.2025 ~13:00-15:00",
        "sell_count": 5,
        "send_count": 25,
        "arrive_count": 30
    },
    {
        "id": 10,
        "store_id": 2,
        "category": "Мебель",
        "photo": "/products/product_10.jpg",
        "title": "Письменный стол",
        "short_desc": "Просторный деревянный стол",
        "count": 15,
        "price": 149.99,
        "currency": "USD",
        "status": ProductStatus.STOCK_PENDING,
        "time_arrive": "14.02.2025 ~09:00-11:30",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 20
    },
    {
        "id": 11,
        "store_id": 3,
        "category": "Электроника",
        "photo": "/products/product_11.jpg",
        "title": "Наушники",
        "short_desc": "Беспроводные наушники с шумоподавлением",
        "count": 0,
        "price": 199,
        "currency": "USD",
        "status": ProductStatus.SELL,
        "time_arrive": "10.12.2024 ~10:00-12:00",
        "time_send": null,
        "sell_count": 80,
        "send_count": 0,
        "arrive_count": 80
    },
    {
        "id": 12,
        "store_id": 1,
        "category": "Мебель",
        "photo": "/products/product_12.jpg",
        "title": "Книжный шкаф",
        "short_desc": "Современный деревянный книжный шкаф",
        "count": 15,
        "price": 99.99,
        "currency": "USD",
        "status": ProductStatus.ARRIVED,
        "time_arrive": "15.12.2024 ~09:00-11:30",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 20
    },
    {
        "id": 13,
        "store_id": 4,
        "category": "Игрушки",
        "photo": "/products/product_14.jpg",
        "title": "Пазл",
        "short_desc": "Сложный пазл для всех возрастов",
        "count": 50,
        "price": 14.99,
        "currency": "USD",
        "status": ProductStatus.SELL,
        "time_arrive": "20.11.2024 ~12:00-14:00",
        "time_send": "25.11.2024 ~13:00-15:00",
        "sell_count": 25,
        "send_count": 25,
        "arrive_count": 50
    },
    {
        "id": 14,
        "store_id": 2,
        "category": "Одежда",
        "photo": "/products/product_13.jpg",
        "title": "Зимняя куртка",
        "short_desc": "Теплая и стильная зимняя куртка",
        "count": 10,
        "price": 89.99,
        "currency": "USD",
        "status": ProductStatus.ARRIVED,
        "time_arrive": "01.01.2025 ~08:00-10:00",
        "time_send": null,
        "sell_count": 5,
        "send_count": 0,
        "arrive_count": 10
    },
    {
        "id": 15,
        "store_id": 3,
        "category": "Книги",
        "photo": "/products/product_15.jpg",
        "title": "Кулинарная книга",
        "short_desc": "Рецепты для быстрых и вкусных блюд",
        "count": 30,
        "price": 24.99,
        "currency": "USD",
        "status": ProductStatus.STOCK_PENDING,
        "time_arrive": "25.01.2025 ~10:00-12:00",
        "time_send": null,
        "sell_count": 0,
        "send_count": 0,
        "arrive_count": 30
    }
]

